### ISSUE TITLE
Request: Add configuration option that allows for type hint in signature _or_ docstring, but not both

### ISSUE THREAD

**Issue by dvmcconnell** [jsh9/pydoclint#106]
We are in the midst of updating our codebase to use type hints in signatures. While `--arg-type-hints-in-docstring` and `--arg-type-hints-in-signature` are great for repositories/projects that are already following one style and want to enforce it, they don't support one in the midst of transitioning between one and the other. With our repositories enforcing flake8 passing via pre-commit and GitHub Actions, we can't turn on pydoclint with either of these options without fully converting the codebase to one or the other.

We'd really like a configuration option that allows for type hints in either one, but not both - something like `--arg-type-hints-in-either`, which checks that type hints are defined in exactly one place, but doesn't care which one they are in. Gradually, we would convert our codebase to using type hints in signatures, and eventually use `--arg-type-hints-in-signature=True` and `--arg-type-hints-in-docstring=False`, taking care of any stragglers.

If this functionality is already available and I'm missing something, please let me know! If not, I'm happy to give it a whirl if you agree it would be nice to have.

**Comment by jsh9** [comment]
Hi @dvmcconnell ,

I think `--arg-type-hints-in-either` may be a bit temporary, and if users use this option as a permanent one, it could lead to code repos that are harder to maintain.

Since you are trying to gradually migrate your code base, could you try `--baseline` and `--generate-baseline`, which ignore existing violations.  The existing violations are logged in a plain text file, and you can manually tweak the file.

**Comment by dvmcconnell** [comment]
Yeah it would absolutely be temporary, I could see repos being harder to maintain as a result in some cases.

The baseline functionality should handle this use case just fine, I'll work with my team to figure out exactly what we want to do here moving forward. Thanks for pointing me to it!
