### ISSUE TITLE
More config control for type hinting in signature

### ISSUE THREAD

**Issue by JessieSteckling** [jsh9/pydoclint#113]
I would like to have an option related to `--arg-type-hints-in-signature` where the tool does not enforce anything related to type hints in the signature. The current options allow linting to either enforce always having type hints or never. For more flexibility in a large project, I would like the option for the tool to enforce neither the absence or the presence of type hints. Multiple contributors on a project might not be able to agree , and flexibility would be nice

**Comment by jsh9** [comment]
Hi @JessieSteckling , my concern is that not enforcing type hints (either the presence or the absence) will promote bad/inconsistent coding style.

I think all the code files in a project should have consistent style.  Otherwise future code maintainers won't know what to do ("should I add type hints? or should I not add type hints?").

If you really don't want to enforce type hints, you can use `noqa` to bypass certain violations, for example, DOC106 to DOC111.

**Comment by jsh9** [comment]
Closing this issue.
