### ISSUE TITLE
[dev] Lint with ruff

### ISSUE THREAD

**Issue by real-yfprojects** [jsh9/pydoclint#27]
I would like to configure [ruff](https://beta.ruff.rs/) as a linter for the our python code. It is very fast and supports all rules known from flake8, pylint,...

**Comment by jsh9** [comment]
I'm using quite a few flake8 plugins in this repo, such as [these](https://github.com/jsh9/pydoclint/blob/88015c7e689881c589e82823f4975ed78c207b87/tox.ini#L36-L53).

I'm not sure ruff has implemented all of these.

pydoclint is a small repo (and I don't think it will become very big eventually), so at least right now, I'm not seeing the linter running time as a bottleneck or an inconvenience.

**Comment by real-yfprojects** [comment]
> I'm not sure ruff has implemented all of these.

I'll check.

> pydoclint is a small repo (and I don't think it will become very big eventually), so at least right now, I'm not seeing the linter running time as a bottleneck or an inconvenience.

I agree.

**Comment by real-yfprojects** [comment]
> > I'm not sure ruff has implemented all of these.
> 
> I'll check.

Many are but not all.

**Comment by ssbarnea** [comment]
Can we have an updated list of rules that are already covered by ruff? I would find very useful to only run ruff and avoid ruinning flake8 with pydoclint or pydoclint separately, especialy as separated it lacks a huge number of important features, like inline noqa.

There are other implications, like lack of a vscode extension, which makes it even more painful.

Out of curiosity, have you considered trying to implement the missing ones in ruff itself, so we would not need pydoclint anymore? -- I know that writing rust code is not as easy or fun as python, but on the long run, it would translate to far less maintenance, as ruff is under heavy development.

**Comment by jsh9** [comment]
Hi @ssbarnea ,

My goal is to make pydoclint as good as I can, and integrating with Ruff is out of the scope of this project.

I believe it is Ruff's authors' responsibility (rather than ours) to find good Python linters and translate them into Rust.  Additionally many authors of these linters (such as myself) don't code in Rust, so we can't really contribute to Ruff.

And honestly, I doubt that Ruff will be sustainable in the long run.  Here are some of my reasons:

1. It is too centralized so it can't move fast enough.  (For example, it seems Ruff's authors may still consider translating darglint.)  
2. The speed benefit it offers do not benefit small repos (such as pydoclint): do you really care about saving a few seconds if your repo is small? 
3. Ruff's coverage is far from comprehensive.  One example is: I use a lot of flake8 plugins that are not implemented in Ruff: https://github.com/jsh9/pydoclint/blob/bf674facc70a002bea0291dc6186b2ce3e266f0c/tox.ini#L40-L57
