### ISSUE TITLE
[dev]: Seperate lint from tests in ci.

### ISSUE THREAD

**Issue by real-yfprojects** [jsh9/pydoclint#28]
This is very useful for understanding why ci fails and it also speeds up the PR checks.
Currently linting errors will fail code tests and one has to click a lot to find out what exactly failed.

In my projects its as simple as running `pre-commit run --all-files`. However here you have configured linters in multiple places. There is pre-commit and there is tox. It might make sense to run some linters for multiple python versions if they can only detect errors for the currently installed version. But I can't make sense  of running formatters for each version.\

What do you think?

**Comment by jsh9** [comment]
Hi @real-yfprojects , some of the linters I use in my `tox.ini` (such as [these](https://github.com/jsh9/pydoclint/blob/88015c7e689881c589e82823f4975ed78c207b87/tox.ini#L39-L51) and [this](https://github.com/jsh9/pydoclint/blob/88015c7e689881c589e82823f4975ed78c207b87/tox.ini#L56-L61)) don't offer pre-commit hooks, so maybe we can't use these linters in pre-commit?

I may be wrong though, because I'm not an expert of using pre-commit (yet).  If you think I'm wrong, please feel free to submit a PR.

Thanks!

**Comment by real-yfprojects** [comment]
They do in the form of [ruff](beta.ruff.rs) or [flake8](https://flake8.pycqa.org/en/latest/user/using-hooks.html).

**Comment by jsh9** [comment]
Thanks for showing me this doc: https://flake8.pycqa.org/en/latest/user/using-hooks.html

I draw this general line between pre-commit and tox:
- pre-commit is for auto-formatting files
- tox is for checking any issues (including code issues, formatting issues, etc.), and ideally no auto-formatting should happen when I run tox

You seem to be drawing the line differently:
- pre-commit is for detecting formatting issues & auto-formatting files
- tox is for detecting code issues (via unit tests, integration tests, ...)

I'm open to your way of drawing the line.  Would you have some time to make some changes and submit a PR?

**Comment by jsh9** [comment]
A tangential topic: I'm a bit skeptical about ruff though.  Because ruff is completely centralized and doesn't support any plugins.  So in many use cases, people will still have to use both flake8 and ruff, which makes maintenance harder.

**Comment by real-yfprojects** [comment]
> You seem to be drawing the line differently

Well actually I don't draw much of a line. Pre-commit enforce rules on commits before they are made. Consequently every chetk including tests theoretically belong there. However this usually isn't practical since the hooks run on every commit while test suites usually take a long time to execute. There is a tradeoff between time and the simplicity and safety of pre-commit hooks.

**Comment by jsh9** [comment]
> This is very useful for understanding why ci fails and it also speeds up the PR checks. Currently linting errors will fail code tests and one has to click a lot to find out what exactly failed.
> 
> In my projects its as simple as running `pre-commit run --all-files`. However here you have configured linters in multiple places. There is pre-commit and there is tox. It might make sense to run some linters for multiple python versions if they can only detect errors for the currently installed version. But I can't make sense of running formatters for each version.\
> 
> What do you think?

I've had some time to think about this, and I think I still prefer to do all the checks (unit tests + code format checks) in `tox`.  In other words, not separate them.

This is because even if we separate the formatting (flake8 and auto-formatters) from `tox`, we'd need to put it in the CI pipeline so that it runs every time we push something to a branch.  (If we don't do that, there's a risk of merging in code with formatting issues.)

Therefore, I'm going to close this issue as "won't fix" for now.  But feel free to add more comments below, or re-open it if you have other reasons.  Thanks!
