### ISSUE TITLE
Long literal types that need a line return are not understood correctly by pydoclint

### ISSUE THREAD

**Issue by erwann-met** [jsh9/pydoclint#38]
Code to reproduce :
![image](https://github.com/jsh9/pydoclint/assets/113345860/d19d3a37-c262-4224-a6aa-2a17fd635cb8)

Here the line return in argument `c`'s type in the docstring is truncated because of the line break.
`pydoclint` therefore thinks types do not match:

![image](https://github.com/jsh9/pydoclint/assets/113345860/93619b96-030c-42aa-8dcf-18722ab7b79b)

(Note that using double quotes does not fix this issue)
Of course a better practice would have been to declare this literal type elsewhere and use it as a constant, but i stumbled into that while linting old code from my company.

**Comment by jsh9** [comment]
Thanks for sharing this example.  Very interesting!

I used this example and stepped through the code.  Here is what I found:

- The type hint of `c` in the function signature is correctly parsed as this string: `"Literal['Option 1', 'Option 2', 'Option 3', 'Option 4', 'Option 5', 'Option 6', 'Option 7', 'Option 8', 'Option 9']"`
- The type hint of `c` in the docstring, however, is parsed as this string: `"Literal['Option 1', 'Option 2', 'Option 3', 'Option 4', 'Option 5',"`

That's the reason why you are seeing DOC105.

Pydoclint uses [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html), the official numpy docstring library, to parse numpy-style docstrings.  As far as I know, numpydoc is a rule-based parser (as opposed to an AI-based parser).

When you put `'Option 6', 'Option 7', 'Option 9', ]` in the 2nd line of the docstring, the parser naturally thinks that it is the description of the argument `c` rather than a part of the type hint.

I remember you mentioned over here (https://github.com/astral-sh/ruff/issues/458#issuecomment-1607335721) that pydoclint doesn't provide informative error messages.

I think your assessment is correct in all these 3 cases you mentioned.  (This one, https://github.com/jsh9/pydoclint/issues/37, and https://github.com/jsh9/pydoclint/issues/36)  All 3 cases share this similarity: the docstring parser gets confused because the docstring doesn't strictly follow the format.

I think it may be infeasible or at least tricky to really provide "on point" error messages in such cases, simply because the intention of the docstring's author is difficult to infer.

**Comment by jsh9** [comment]
The more I think about these 3 cases you raised, the more I think we need **_another_** linter that specializes in checking just the style of docstrings.  It can be named "numpydocstyle" 😂 

In pydocslint's README, I actually recommend people use both pydoclint and pydocstyle together: 
https://github.com/jsh9/pydoclint/blob/1a3596f641a83a0847931f803a32294f353cbb3e/README.md?plain=1#L27-L28

The underlying reason is the same: pydoclint's scope is to compare docstring against function signatures.  The narrower the scope, the better a job it can do.

**Comment by erwann-met** [comment]
I think you are completely right, ideally we want to use `ruff` (or pydocstyle) for auto formatting and `pydoclint` for type check.
If those cases cannot be addressed within the scope of `pydoclint` then so be it.

Honestly the minute pydocstyle rule D410 is fixed we'll switch from flake8/darglint to ruff/pydoclint.
The two other issues are very minor hindrance, I just wanted to let you know!

I would like to thank you on behalf on my coworkers for the amazing work you made on `pydoclint` in so little time.

**Comment by jsh9** [comment]
Thank you!  I'm glad that I'm work can be of help to your team.

Btw, you mentioned that pydoclint couldn't ignore certain rules.  If you use pydoclint with flake8, you can use `# noqa: DOC...` to ignore certain rules inline.

Do you think running flake8 + pydoclint will be very slow for your projects?  I'm personally happy with flake8's speed, probably because I don't deal with large monolith code bases.

The "native" pydoclint doesn't support inline ignoring, because I thought piggybacking flake8's inline ignore is fine.  If it is really necessary, I can consider adding inline ignoring.

**Comment by jsh9** [comment]
Closing this issue.  No action needed.

**Comment by jsh9** [comment]
(If I closed this issue by accident, please feel free to leave a comment here.)
