### ISSUE TITLE
Feature request: sphinx

### ISSUE THREAD

**Issue by wwuck** [jsh9/pydoclint#43]
Hi,  this is a feature request to support the sphinx docstring style.

Thanks

**Comment by jsh9** [comment]
I procrastinated a bit but this day has eventually come 😂

Yes, this is something that I could add.

Could you confirm that this is the official guide/rules of the Sphinx docstring style?  https://sphinx-rtd-tutorial.readthedocs.io/en/latest/docstrings.html

Thanks!

**Comment by jsh9** [comment]
Thanks!

pydoclint uses docstring-parser to parse Google-style docstrings, and I know it can also parse Sphinx-style docstrings:

https://github.com/jsh9/pydoclint/blob/062bb451c3b22cd8ce460417d88f1690c9710037/setup.cfg#L21

The reason I'm asking for a style guide is for me to write test cases.  I haven't really used the Sphinx style before.

**Comment by jsh9** [comment]
Hi @wwuck:

I added support for the Sphinx docstring style.  It's in the latest release (v0.1.0).

Please feel free to try it out.  Since I'm not very familiar with this style, I don't know what different variations of this style can there be.

If you find any issues or false positives, please feel free to open other issues.  Thanks!
