### ISSUE TITLE
Docs request: are ignores possible when not in `flake8` mode?

### ISSUE THREAD

**Issue by jamesbraza** [jsh9/pydoclint#96]
https://jsh9.github.io/pydoclint/how_to_ignore.html documents ignoring violations when in `flake8` mode.

Can we also document how to ignore violations when not in `flake8` mode (is it possible)? Thank you in advance 👌

**Comment by jsh9** [comment]
It is not possible at the moment.  Mainly because I don't want to reinvent the wheel by duplicating what flake8 has done.

If there are high demands for it, or if running pydoclint as a flake8 plugin has serious performance implications (which I don't think so, based on my current understanding), I can consider implementing it.  (Contributions are always welcome.)

**Comment by jamesbraza** [comment]
Okay, thank you for answering!  I will leave this open, cuz I think that should be added to the docs somewhere.  Otherwise, feel free to close this out

**Comment by jamesbraza** [comment]
I guess the issue I am hitting is `ruff`'s [`RUF100`](https://docs.astral.sh/ruff/rules/unused-noqa/) is cleaning up `noqa`'s I add for `pydoclint` 🙁

**Comment by jsh9** [comment]
It's already documented here in README (Section 2.4): https://github.com/jsh9/pydoclint#24-native-vs-flake8

So I'll close this issue out.
